### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by carandraug** [macronucleus/chromagnon#1]
* chromagnon has non-optional dependencies on fftw and bioformats
* fftw and bioformats are released under GPL
* chromagnon licence is not GPL compatible

IANAL but does that not make chromagnon undistributable?  I would appreciate any clarification on the issue.

**Comment by macronucleus** [comment]
I understand your concern. Let me consult agents in our research institute.

**Comment by carandraug** [comment]
On 9 April 2017 at 08:33, Atsushi Matsuda <macronucleus@fbs.osaka-u.ac.jp> wrote:
> [...]
> The license was created by someone in our institute.
> I am trying to consult him about the issue.

I was wondering if this has been discussed yet?

**Comment by macronucleus** [comment]
Yes, we've been discussing this issue.
Unfortunately it's in the middle of long holidays in Japan now.
I guess we'll reach some decision in the next week.
Thank you.

iPhoneから送信

2017/05/03 1:00、Carnë Draug <notifications@github.com> のメッセージ:

**Comment by carandraug** [comment]
> Unfortunately it's in the middle of long holidays in Japan now. I guess we'll reach some decision in the next week.

Has there been any news on this front?

**Comment by macronucleus** [comment]
I have changed the license to GPL in early May, but I wanted to change the Document as well.
I was too ambitious to change installation parts as well, but it took too much time, and again I did not have time to do it.
Anyway, I changed only the corresponding part of the document now.
I am sorry for the delay.
