### ISSUE TITLE
reference files with different wavelengths crash program

### ISSUE THREAD

**Issue by iandobbie** [macronucleus/chromagnon#12]
I have a refernce file with 544,605 wavelengths, the target file has 515,605. On windows this generates the message below rather than a useful error. 

Traceback (most recent call last):

********************************************
  File "Chromagnon\threads.py", line 213, in run

********************************************
  File "Chromagnon\aligner.py", line 811, in loadParm

********************************************
  File "Chromagnon\chromformat.py", line 196, in __init__

********************************************
  File "Chromagnon\chromformat.py", line 286, in loadParm

********************************************
AttributeError: 'Chromagnon' object has no attribute 'fn'

**Comment by macronucleus** [comment]
I have confirmed.
Yes the error message does not make sense.

Currently, the program proceeds even if some channels are missing in the target file, but I guess this is not what is expected for users.
I am going to change the behavior as follows:
  - When no or only one wavelength is in common, then the program shows a warning message and quits.
  - When at least two wavelengths are in common, then the program proceeds to align the common two channels and leaves the uncommon channels unaligned.

Any comments?

**Comment by macronucleus** [comment]
The wavelength mismatch issue was finally fixed with the new binary release `v0.70`.
