### ISSUE TITLE
Casting complex values to real discards the imaginary part

### ISSUE THREAD

**Issue by carandraug** [macronucleus/chromagnon#13]
We get the following warning running Chromagnon:

```
/usr/local/lib/python2.7/dist-packages/Chromagnon/Priithon/fftfuncs.py:15: ComplexWarning: Casting complex values to real discards the imaginary part
   return N.fromfunction(f,s).astype(t)
```

I'm guessing this is by design but then the warning should be silenced explicitely

**Comment by carandraug** [comment]
We're running Chromagnon on python 2.7 in Debian stable (stretch) with javabridge 1.0.18, tifffile  0.15.1, python-bioformats 1.5.2, numpy 1.12, and scipy 0.18.

**Comment by macronucleus** [comment]
I don't recall when I did it, but the warning was suppressed already (probably before `v0.69`?). I am sorry for the late reply.
