### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NRanta** [macronucleus/chromagnon#15]
The pdf for documentation on how the code works is missing.  Clicking on the link gives a "Not Found" page for the pdf.  Is there somewhere else that has the document?  Thank you.

**Comment by macronucleus** [comment]
Thank you very much for pointing out the broken link.
I also found that the link for the download page was also broken.
I am sorry about that.
I have fixed the links now.

**Comment by NRanta** [comment]
Thank you very much for the quick response to the issue!
