### ISSUE TITLE
Unclear: Defining reference image

### ISSUE THREAD

**Issue by NRanta** [macronucleus/chromagnon#16]
It is not clear how to define the reference image.  There is a target and reference image that are required and shown in the documentation, but I am not fully understanding this.  The target appears to refer to the image that you are interested in, but the source of the reference image is unclear.  Can you please help me understand what I should be doing to get the reference image necessary?  Thank you.

**Comment by macronucleus** [comment]
Yes the target image is the one that you are interested in. However, often you cannot directly measure chromatic shift of the target image, and thus you will need the "reference image", which is a  dedicated image to measure chromatic shift in the target image. On page 5 and 6 in the document, there are two ways to obtain the reference images. Depending on microscopy, you will need different samples or dyes of shorter wavelengths. 
Does the above explanation make sense to you?
Let me know if it is still unclear.
I will try to update the document to clarify this.
