### ISSUE TITLE
no license in the repository

### ISSUE THREAD

**Issue by neuromusic** [macronucleus/chromagnon#19]
Hello!

Very interested in your work here, as it looks highly relevant to https://github.com/spacetx/starfish/issues/1336

However, the repository is missing a license for use and redistribution. LICENSE.md contains the changelog (through v0.6)

Can you please add a license to the repository so that we can consider whether it meets our needs?

Thanks!

**Comment by macronucleus** [comment]
Thank you for pointing out the mistake, and introducing an interesting project.
I have restored `LICENSE.md`, which is GPL, since the program depends on a GPL package (`Bioformats`) to read more file formats.
