### ISSUE TITLE
package installation could delcare chromagnon entry_point

### ISSUE THREAD

**Issue by carandraug** [macronucleus/chromagnon#5]
setuptools has support to declare entry_points.  This means that installing with pip would automatically generate a program named chromagnon instead of requiring users to specify the path for `chromagnon/main.py`

I am not a Windows or Mac user but my understanding is that setuptools even handles the case of correctly using pythonw for systems where required.

**Comment by macronucleus** [comment]
Thank you for pointing out.
I have added entry_point to linux version.
On Windows and Mac, this did not work for me, but script option worked like entry_point.
I also updated document describing how to use it.
