### ISSUE TITLE
source releases are missing ndviewer and imgio subpackages

### ISSUE THREAD

**Issue by carandraug** [macronucleus/chromagnon#9]
I have downloaded the source release for `v0.6` and installation fails:

```
$ python setup.py install
[...]
error: package directory 'Chromagnon/ndviewer' does not exist
```

and indeed the directory does not exist.

I am installing:

$ md5sum Chromagnon-0.6.tar.gz 
ec246671416ec06c9cc0b685a07c6d40  ../Chromagnon-0.6.tar.gz

which appears listed as the last release on the repo releases. (by the way, it's a bit confusing that the same release has binary release with the number v0.64 instead of v0.6)

**Comment by macronucleus** [comment]
Thank you for pointing out.
The commit linked to the release was updated, and the release tag was also changed to `v0.64`.
